services:
  react-app:
    build:
      context: ./client
    stdin_open: true
    ports:
      - 3000:3000
    networks:
      - mern-app
    restart: always

  api-server:
    build:
      context: ./server
    ports:
      - 5000:5000
    networks:
      - mern-app
    depends_on:
      mongo:
        condition: service_healthy
    restart: always

  mongo:
    image: mongo:6
    ports:
      - 27017:27017
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  mern-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local
  mongo-config:
    driver: local
